openapi: 3.2.0
info:
  title: DMI Backend Infra API
  version: 0.1.0
tags:
- name: Infra
paths:
  /healthz:
    get:
      tags:
      - Infra
      summary: Healthz
      operationId: healthz_healthz_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
                title: Response Healthz Healthz Get
